/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shifu.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import org.jdom2.Element;
import shifu.core.tools.xml.XmlParser;
import shifu.model.Livre;
import shifu.model.dao.ShifuDAOFactory;

/**
 *
 * @author delwiv
 */
public class MenuBar extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public MenuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miQuit = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        miAddOuvrage = new javax.swing.JMenu();
        miGestionOuvrages = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        miConsultOuvrage = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miGestionAdherents = new javax.swing.JMenuItem();
        miAddAdherent = new javax.swing.JMenuItem();
        miVoirAdherentsAValider = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("Fichier");
        jMenu1.setName("jMenu1"); // NOI18N

        miQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miQuit.setText("Quitter");
        miQuit.setName("miQuit"); // NOI18N
        jMenu1.add(miQuit);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Importer depuis Bookin");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        miAddOuvrage.setText("Ouvrages");
        miAddOuvrage.setName("miAddOuvrage"); // NOI18N

        miGestionOuvrages.setText("Gestion des Ouvrages");
        miGestionOuvrages.setName("miGestionOuvrages"); // NOI18N
        miAddOuvrage.add(miGestionOuvrages);

        jMenuItem2.setText("Ajouter un ouvrage");
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        miAddOuvrage.add(jMenuItem2);

        miConsultOuvrage.setText("Consulter un ouvrage");
        miConsultOuvrage.setName("miConsultOuvrage"); // NOI18N
        miAddOuvrage.add(miConsultOuvrage);

        jMenuBar1.add(miAddOuvrage);

        jMenu3.setText("Adhérents");
        jMenu3.setName("jMenu3"); // NOI18N

        miGestionAdherents.setText("Gestion des adhérents");
        miGestionAdherents.setName("miGestionAdherents"); // NOI18N
        jMenu3.add(miGestionAdherents);

        miAddAdherent.setText("Ajouter un adhérent");
        miAddAdherent.setName("miAddAdherent"); // NOI18N
        jMenu3.add(miAddAdherent);

        miVoirAdherentsAValider.setText("Voir adhérents à valider");
        miVoirAdherentsAValider.setName("miVoirAdherentsAValider"); // NOI18N
        jMenu3.add(miVoirAdherentsAValider);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Emprunts");
        jMenu4.setName("jMenu4"); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        List<Livre> listLivres = new ArrayList();
        JFileChooser fileChooser = new JFileChooser();
        int responseVal = fileChooser.showOpenDialog( new JFrame() );

        if ( responseVal == JFileChooser.APPROVE_OPTION ) {
            listLivres = getLivresFromXml( fileChooser.getSelectedFile().getAbsolutePath() );

//                    livresBookin = parseFile( fileChooser.getSelectedFile().getAbsolutePath() );
            ListIterator it = listLivres.listIterator( 0 );
            while ( it.hasNext() ) {
                Livre cur = ( Livre ) it.next();
                try {
                    //                        System.out.println( cur.toString() );
                    ShifuDAOFactory.getLivreDAOC().create( cur );
                } catch ( SQLException ex ) {
//                    Logger.getLogger( MenuBar.class.getName() ).log( Level.SEVERE, null, ex );
                }
                
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private List<Livre> getLivresFromXml( String absolutePath ) {
        List<Livre> listLivre = new ArrayList();

        XmlParser xmlParser = new XmlParser( absolutePath );

        List<Element> listElement = xmlParser.getRacine().getChildren( "Book" );
        ListIterator it = listElement.listIterator( 0 );

        while ( it.hasNext() ) {
            try {
                listLivre.add( new Livre( ( Element ) it.next() ) );
            } catch ( Exception ex ) {
                ex.printStackTrace();
            }
        }
        return listLivre;

    }

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger( MenuBar.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger( MenuBar.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger( MenuBar.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( MenuBar.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new MenuBar().setVisible( true );
            }
        } );
    }

    public JMenuItem getMiAddAdherent() {
        return miAddAdherent;
    }

    public JMenu getMiAddOuvrage() {
        return miAddOuvrage;
    }

    public JMenuItem getMiConsultOuvrage() {
        return miConsultOuvrage;
    }

    public JMenuItem getMiGestionOuvrages() {
        return miGestionOuvrages;
    }

    public JMenuItem getMiQuit() {
        return miQuit;
    }

    public JMenuItem getMiVoirAdherentsAValider() {
        return miVoirAdherentsAValider;
    }

    public JMenuItem getMiGestionAdherents() {
        return miGestionAdherents;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JMenu jMenu1;
    protected javax.swing.JMenu jMenu3;
    protected javax.swing.JMenu jMenu4;
    protected javax.swing.JMenuBar jMenuBar1;
    protected javax.swing.JMenuItem jMenuItem1;
    protected javax.swing.JMenuItem jMenuItem2;
    protected javax.swing.JMenuItem miAddAdherent;
    protected javax.swing.JMenu miAddOuvrage;
    protected javax.swing.JMenuItem miConsultOuvrage;
    protected javax.swing.JMenuItem miGestionAdherents;
    protected javax.swing.JMenuItem miGestionOuvrages;
    protected javax.swing.JMenuItem miQuit;
    protected javax.swing.JMenuItem miVoirAdherentsAValider;
    // End of variables declaration//GEN-END:variables
}
