/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shifu.view.panel;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author delwiv
 */
public class PanelImporterFichier extends javax.swing.JPanel {

    /**
     * Creates new form PanelImporterJSON
     */
    public PanelImporterFichier() {
        initComponents();
    }

    public JButton getBtnAnnuler() {
        return btnAnnuler;
    }

    public JButton getBtnChoisirFichier() {
        return btnChoisirFichier;
    }

    public JButton getBtnImport() {
        return btnImport;
    }

    public JTable getTabLivres() {
        return tabLivres;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btnChoisirFichier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabLivres = new javax.swing.JTable();
        btnImport = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        jFileChooser1.setName("jFileChooser1"); // NOI18N

        btnChoisirFichier.setText("Choisir un fichier json");
        btnChoisirFichier.setName("btnChoisirFichier"); // NOI18N
        btnChoisirFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoisirFichierActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabLivres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabLivres.setName("tabLivres"); // NOI18N
        jScrollPane1.setViewportView(tabLivres);

        btnImport.setText("Importer en DB");
        btnImport.setName("btnImport"); // NOI18N

        btnAnnuler.setText("Annuler");
        btnAnnuler.setName("btnAnnuler"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChoisirFichier)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnnuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImport)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChoisirFichier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(btnAnnuler))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoisirFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoisirFichierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoisirFichierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnAnnuler;
    protected javax.swing.JButton btnChoisirFichier;
    protected javax.swing.JButton btnImport;
    protected javax.swing.JFileChooser jFileChooser1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable tabLivres;
    // End of variables declaration//GEN-END:variables
}
