/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shifu.view.panel;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.ListIterator;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import shifu.model.Ouvrage;

/**
 *
 * @author delwiv
 */
public class PanelGoogleResponse extends javax.swing.JPanel {

    private List<Ouvrage> listOuvrages;
    private Ouvrage ouvrage;

    /**
     * Creates new form PanelGoogleResponse
     *
     * @param listOuvrages
     */
    public PanelGoogleResponse( List<Ouvrage> listOuvrages ) {
        initComponents();
        this.listOuvrages = listOuvrages;
        DefaultTableModel model = ( DefaultTableModel ) this.tableOeuvre.getModel();
        model.setRowCount( 0 );
        ListIterator it = this.listOuvrages.listIterator( 0 );

        while ( it.hasNext() ) {
            Ouvrage ouvrage = ( Ouvrage ) it.next();
            model.addRow( new Object[]{
                ouvrage.getTitre(),
                ouvrage.getSousTitre(),
                ouvrage.getStrAuteurs(),
                ouvrage.getLangue() } );
        }
        this.tableOeuvre = new JTable( model );
//
//            @Override
//            public void valueChanged( ListSelectionEvent e ) {
//                ouvrage = listOuvrages.get( e.getFirstIndex());
//            }
//        });
        this.setVisible( true );

    }

    public List<Ouvrage> getListOuvrages() {
        return listOuvrages;
    }

    public JButton getBtnCancel() {
        return btnCancel1;
    }

    public JButton getBtnValid() {
        return btnValid;
    }

    public JTable getTableOeuvre() {
        return tableOeuvre;
    }

    public void setListOuvrages( List<Ouvrage> listOuvrages ) {
        this.listOuvrages = listOuvrages;
    }

    public Ouvrage getLivre() {
        return this.ouvrage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOeuvre = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnValid = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();

        btnCancel.setText("Annuler");
        btnCancel.setName("btnCancel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableOeuvre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre", "Sous-titre", "Auteur(s)", "Langue"
            }
        ));
        tableOeuvre.setName("tableOeuvre"); // NOI18N
        tableOeuvre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOeuvreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOeuvre);

        jPanel1.setName("jPanel1"); // NOI18N

        btnValid.setText("OK");
        btnValid.setName("btnValid"); // NOI18N

        btnCancel1.setText("Annuler");
        btnCancel1.setName("btnCancel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnValid)
                .addComponent(btnCancel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableOeuvreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOeuvreMouseClicked
        // TODO add your handling code here:
        int rowSelected = tableOeuvre.rowAtPoint( evt.getPoint() );
        ouvrage = listOuvrages.get( rowSelected );
    }//GEN-LAST:event_tableOeuvreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnCancel;
    protected javax.swing.JButton btnCancel1;
    protected javax.swing.JButton btnValid;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable tableOeuvre;
    // End of variables declaration//GEN-END:variables

}
