/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shifu.view.panel;

import java.sql.Date;
import javax.swing.JButton;
import shifu.core.AbstractShifuView;
import shifu.model.Adherent;
import shifu.view.ViewAdherent;

/**
 *
 * @author user
 */
public class PanelAjouterAdherent extends javax.swing.JPanel {

    private Adherent adherent;
    private ViewAdherent parent;

    public JButton getBtnAnnuler() {
        return btnAnnuler;
    }

    public JButton getBtnValiderAjoutAdherent() {
        return btnValiderAjoutAdherent;
    }

    public void clearPanel() {
        setPrenom( "" );
        setNom( "" );
        setEmail( "" );
        setTel( "" );
        this.panelFormulaireAdherent1.getDateChooserNaissance().setDate( null );
        this.panelFormulaireAdherent1.setTextAdresse( "" );
        this.panelFormulaireAdherent1.setTextBatiment( "" );
        this.panelFormulaireAdherent1.setTextAppart( "" );
        this.panelFormulaireAdherent1.setTextCp( "" );
        this.panelFormulaireAdherent1.setTextVille( "" );
    }

    /**
     * Creates new form PanelCreeAdherent
     */
    public PanelAjouterAdherent() {
        initComponents();
    }

    public PanelFormulaireAdherent getPanelFormulaireAdhérent1() {

        return panelFormulaireAdherent1;
    }

    public void setPanelFormulaireAdhérent1( PanelFormulaireAdherent panelFormulaireAdherent1 ) {

        this.panelFormulaireAdherent1 = panelFormulaireAdherent1;
    }

    public String getNom() {
        return panelFormulaireAdherent1.getNom();
    }

    public void setNom( String nom ) {
        this.panelFormulaireAdherent1.setNom( nom );
    }

    public String getPrenom() {
        return panelFormulaireAdherent1.getPrenom();
    }

    public void setPrenom( String prenom ) {
        this.panelFormulaireAdherent1.setPrenom( prenom );
    }

    public String getTitre() {
        return panelFormulaireAdherent1.getTitre();
    }

    public void setTitre( String titre ) {
        this.panelFormulaireAdherent1.setTitre( titre );
    }

    public String getEmail() {
        return panelFormulaireAdherent1.getEmail();
    }

    public void setEmail( String email ) {
        this.panelFormulaireAdherent1.setEmail( email );
    }

    public String getTel() {
        return panelFormulaireAdherent1.getTel();
    }

    public void setTel( String tel ) {
        this.panelFormulaireAdherent1.setTel( tel );
    }

    public Date getDateNaissance() {
        return panelFormulaireAdherent1.getDateNaissance();
    }

//    public void setDateNaissance(String dateNaissance) {
//        this.panelFormulaireAdherent1.setDateNaissance(dateNaissance);
//    }
    public String getligne1() {
        return panelFormulaireAdherent1.getTextAdresse();

    }

    public String getligne2() {
        return panelFormulaireAdherent1.getTextBatiment();

    }

    public String getligne3() {
        return panelFormulaireAdherent1.getTextAppart();

    }

    public String getCp() {
        return panelFormulaireAdherent1.getCp();
    }

    public String getVille() {
        return panelFormulaireAdherent1.getVille();
    }

    public AbstractShifuView getParentView() {
        return parent;
    }

    public void setParentView( ViewAdherent parent ) {
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValiderAjoutAdherent = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelFormulaireAdherent1 = new shifu.view.panel.PanelFormulaireAdherent();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        setMaximumSize(new java.awt.Dimension(769, 358));
        setMinimumSize(new java.awt.Dimension(800, 358));

        btnValiderAjoutAdherent.setText("Valider");
        btnValiderAjoutAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderAjoutAdherentActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Ajouter un adhérent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnnuler)
                        .addGap(18, 18, 18)
                        .addComponent(btnValiderAjoutAdherent))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(panelFormulaireAdherent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormulaireAdherent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValiderAjoutAdherent)
                    .addComponent(btnAnnuler))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnValiderAjoutAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderAjoutAdherentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderAjoutAdherentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnValiderAjoutAdherent;
    private javax.swing.JLabel jLabel1;
    private shifu.view.panel.PanelFormulaireAdherent panelFormulaireAdherent1;
    // End of variables declaration//GEN-END:variables
}
