/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package shifu.view.panel;

import javax.swing.JComboBox;
import shifu.core.AbstractShifuView;
import shifu.view.ViewAuteur;

/**
 *
 * @author user
 */
public class PanelFormulaireAuteur extends javax.swing.JPanel {
    private int id;
    private String nom;
    private String prenom ;
    private String surnom;
    private String commentaire;
    private ViewAuteur parentView;
    /**
     * Creates new form PanelAuteur
     */
    public PanelFormulaireAuteur() {
        initComponents();
    }

    public String getNationalite() {
        return cbbNationalite.getSelectedItem().toString();
    }

    public int getId() {
        return Integer.parseInt(textID.getText());
    }

    public void setId(int id) {
        this.textID.setText(String.valueOf(id));
    }

    public String getNom() {
        return textNom.getText();
    }

    public void setNom(String nom) {
        this.textNom.setText(nom);
    }

    public String getPrenom() {
        return  textPrenom.getText();
    }

    public void setPrenom(String prenom) {
        this.textPrenom.setText(prenom);
    }

    public String getSurnom() {
        return textSurnom.getText();
    }

    public void setSurnom(String surnom) {
        this.textSurnom.setText(surnom);
    }

    public String getCommentaire() {
        return textCommentaire.getText();
    }

    public void setCommentaire(String commentaire) {
        this.textCommentaire.setText(commentaire);
    }

    public AbstractShifuView getParentView() {
        return parentView;
    }

    public void setParentView(ViewAuteur parentView) {
        this.parentView = parentView;
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        textNom = new javax.swing.JTextField();
        textPrenom = new javax.swing.JTextField();
        textSurnom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textCommentaire = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cbbNationalite = new javax.swing.JComboBox();

        jButton3.setText("jButton3");

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));

        jLabel1.setText("Nom");

        jLabel2.setText("Prénom");

        jLabel3.setText("Surnom");

        jLabel4.setText("Commentaire");
        jLabel4.setToolTipText("");

        jLabel5.setText("ID");

        textID.setText(" ");

        textCommentaire.setColumns(20);
        textCommentaire.setRows(5);
        jScrollPane1.setViewportView(textCommentaire);

        jLabel6.setText("Nationalité");

        cbbNationalite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Francais", "Anglais", "Chinois" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textID, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(textNom)
                                .addComponent(textPrenom)
                                .addComponent(textSurnom))
                            .addComponent(cbbNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textSurnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbNationalite;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textCommentaire;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textPrenom;
    private javax.swing.JTextField textSurnom;
    // End of variables declaration//GEN-END:variables
}
