/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shifu.view.panel;

import java.sql.SQLException;
import java.util.List;
import java.util.ListIterator;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import shifu.model.Auteur;
import shifu.model.dao.CustomArgument;
import shifu.model.dao.ShifuDAOFactory;

/**
 *
 * @author user
 */
public class PanelAjouterAuteurOeuvre extends javax.swing.JPanel {

    List<Auteur> listAuteurs;

    /**
     * Creates new form PanelAjouterAuteurOeuvre
     *
     * @param currentAuteurs
     */
    public PanelAjouterAuteurOeuvre( List<Auteur> currentAuteurs ) throws SQLException {
        initComponents();
        listAuteurs = ShifuDAOFactory.getAuteurDAO().getByEqualsCustomArgument( new CustomArgument( "1", "1" ) );
        refreshJTable( listAuteurs, currentAuteurs );
    }

    public List<Auteur> getListAuteurs() {
        return listAuteurs;
    }

    public void addAuteur( Auteur auteur ) {
        this.listAuteurs.add( 0, auteur );
        // MAJ liste
        DefaultTableModel model = ( DefaultTableModel ) tableAuteur.getModel();
        model.addRow( new Object[]{
            true,
            auteur.getNom(),
            auteur.getPrenom(),
            auteur.getSurnom(),
            auteur.getNationalite().getLib()
        } );
        tableAuteur = new JTable( model );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnValider = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelSearch1 = new shifu.view.panel.PanelSearch();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAuteur = new javax.swing.JTable();
        btnAjouterAuteur = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Selectionner un auteur");

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));

        tableAuteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "...", "Nom", "Prénom", "Surnom", "Nationalité"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAuteur);
        if (tableAuteur.getColumnModel().getColumnCount() > 0) {
            tableAuteur.getColumnModel().getColumn(0).setMinWidth(20);
            tableAuteur.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        btnAjouterAuteur.setText("Ajouter un auteur");
        btnAjouterAuteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterAuteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAjouterAuteur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(panelSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouterAuteur))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnnuler)
                        .addGap(18, 18, 18)
                        .addComponent(btnValider))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValider)
                    .addComponent(btnAnnuler))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnAjouterAuteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterAuteurActionPerformed

    // TODO add your handling code here:

    }//GEN-LAST:event_btnAjouterAuteurActionPerformed

    public JButton getBtnAjouterAuteur() {
        return btnAjouterAuteur;
    }

    public JButton getBtnAnnuler() {
        return btnAnnuler;
    }

    public JButton getBtnValider() {
        return btnValider;
    }

    public PanelSearch getPanelSearch() {
        return panelSearch1;
    }

    public JTable getTableAuteur() {
        return tableAuteur;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterAuteur;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private shifu.view.panel.PanelSearch panelSearch1;
    private javax.swing.JTable tableAuteur;
    // End of variables declaration//GEN-END:variables

    public final void refreshJTable( List<Auteur> listAuteurs ) {
        this.listAuteurs = listAuteurs;
        DefaultTableModel model = ( DefaultTableModel ) tableAuteur.getModel();
        model.setRowCount( 0 );
        
        ListIterator it = listAuteurs.listIterator( 0 );

        while ( it.hasNext() ) {
            Auteur currentAuteur = ( Auteur ) it.next();
            Object[] row = {
                false,
                currentAuteur.getNom(),
                currentAuteur.getPrenom(),
                currentAuteur.getSurnom(),
                currentAuteur.getNationalite().getLib()
            };
            model.addRow( row );
        }
        this.tableAuteur = new JTable( model );
    }

    public final void refreshJTable( List<Auteur> listAuteurs, List<Auteur> currentAuteurs ) {
        this.listAuteurs = listAuteurs;
        refreshJTable( listAuteurs );
    }
}
